### ISSUE TITLE
Set up gitobox as remote helper for git

### ISSUE THREAD

**Issue by JosuaKrause** [remram44/gitobox#12]
I just found this article on how to set up a remote helper for git (https://rovaughn.github.io/2015-2-9.html) It would be really neat to define a remote `dropbox://path-to-repo` or `gitobox://path-to-repo` which starts/utilizes gitobox.

**Comment by remram44** [comment]
The problem is, you need a daemon running to catch all changes as they happen, and then they are recorded in a Git repo so you get them directly. But you could have a first fetch/push register it with a global daemon or something like that... Hmm.

**Comment by anatol** [comment]
I came to the same idea while playing with droxi tool https://github.com/jangler/droxi/issues/6

It would be great to have a remote helper for git that makes push/pull to Dropbx transparent. The best way to do it is to use Dropbox API to implement git-remote-dropbox script.

**Comment by remram44** [comment]
The way such a tool would work is completely separate from what Gitobox does. I have no intention of rewriting this to use the API.
